### PR TITLE
make vcs ignores available for subprojects

### LINKED ISSUE #6: Slow `project-find-file` with bigger projects
Hello!

I have noticed that `project-find-file` is now really slow (when working with bigger monorepo) while using package with below option enabled:
```lisp
(add-to-list 'project-find-functions #'project-rootfile-try-detect)
```

It may be worth to mention in README about this and e.g. advice to set variable `project-vc-ignores` like so:
```lisp
(setq project-vc-ignores
      '("node_modules"
        "target"
        "build"
        "output"
        "dist"
        "tmp"))
```
Or maybe somehow mitigate this slowness in package itself. What do you think?

Best wishes,
alternateved

### PR DESCRIPTION
**Pull request by buzztaiki**
fixes #6

### CODE REVIEW

**Comment by buzztaiki** [comment]
hm.

**Comment by buzztaiki** [comment]
@alternateved Can you check to see if this patch solves your issue?

**Comment by alternateved** [comment]
I did not check it thoroughly, but it seems that this branch fixes that issue; `project-find-file` works like it used to, without hanging.

**Comment by buzztaiki** [comment]
Thank you!

**Pull request merged**
